### PR TITLE
Upgrade library to support Moya 10 and RxSwift 4

### PR DESCRIPTION
**Pull request by esam091**

### CODE REVIEW

**Comment by gperdomor** [comment]
@esam091 Thanks for the PR :D... Looks good 👍 

Can you fix the tests please?

**Comment by gperdomor** [comment]
Carthage files should be fixed to reflect the new version of Moya and Unbox

**Comment by esam091** [comment]
Sure, just let me know if there is anything else needs to be fixed, I'll finish in a couple of days 🙂

**Comment by gperdomor** [comment]
nothing more for now 😄

**Pull request closed without merging**
